### ISSUE TITLE
Switch node config is broken

### ISSUE THREAD

**Issue by member68** [rsenden/node-red-contrib-property-mapping#5] opened 2020-11-30 11:22 UTC
When trying to configure the switch node, I can't choose the outputs that should be shown at the bottom of the dialog.

![image](https://user-images.githubusercontent.com/321320/100604145-6c9d4a80-3306-11eb-86d8-a4f243fae2c7.png)

This means I loose all outputs everytime I save this node.

**Comment by gelse** [comment] 2021-02-21 20:40
i can confirm this bug.

any plans to fix it or is this contrib abandoned ?

**Comment by rsenden** [comment] 2021-02-23 15:03
In my Node-RED instance I'm still actively using this contrib, just did a quick test and can't reproduce this issue:

![image](https://user-images.githubusercontent.com/8635138/108860941-ff404380-75ee-11eb-9ee3-d375260e79a7.png)

I just found out though that I'm still running quite an old version of Node-RED, apparently the nodered/node-red-docker repo that I'm using has been deprecated. 

I'll need to upgrade Node-RED and then try to reproduce this issue, I'm not sure though when I'll have time for that. I'm happy to accept a pull request if someone manages to fix this issue before I have a chance to upgrade my Node-RED instance.

**Comment by rsenden** [comment] 2021-02-23 17:14
Can you please test with the new version 1.0.4? This new version should fix this issue on the latest Node-RED versions (I've done some quick tests on Node-RED v1.2.9).

**Comment by gelse** [comment] 2021-02-23 19:15
hm, it's not in the store yet and it's no official release.
i will try later to get it manually working.

**Comment by rsenden** [comment] 2021-02-23 19:51
> hm, it's not in the store yet and it's no official release.
> i will try later to get it manually working.

Sorry, I didn't notice that publishing of the new version failed. The new 1.0.4 version has now been correctly published, can you please try again?

**Comment by gelse** [comment] 2021-02-23 20:07
yes, it works now!
big thanks for fixing it so quick!

**Comment by rsenden** [comment] 2021-02-24 08:17
Thanks for the feedback, I will close the issue now.

**Closed as completed by rsenden** 2021-02-24 08:17 UTC
